<<<<<<< HEAD
stages:
  - test

test_api:
  image: python:3.11-slim
  stage: test
  before_script:
    - pip install --no-cache-dir -r requirements.txt
  script:
    - pytest --maxfail=5 --disable-warnings --html=report.html
  artifacts:
    paths:
      - report.html
    when: always
=======
stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

test_api:
  stage: test
  image: python:3.11-slim
  script:
    - pip install --no-cache-dir -r requirements.txt
    - pytest --maxfail=5 --disable-warnings --html=report.html
  artifacts:
    paths:
      - report.html
    expire_in: 1 week
>>>>>>> 9c8f60a3560ca6190b5dfcd69ee27e76aa6f5e64
